import { NextResponse } from 'next/server';
import pool from '../../../../lib/db';

// This route is to add a new playlist to the database for the user that is currently logged in
// It will take in the fields: playlist_name and mood_tag. The user_id will be taken from the session cookie and the playlist_id will be generated by the database.
export async function POST(request) {
  try {
    const cookieUserId = request.cookies.get('karaoke_user_id')?.value;
    const userId = Number(cookieUserId);

    if (!Number.isInteger(userId) || userId < 1) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await request.json();
    const playlistName = body.playlistName?.trim();
    const moodTag = body.moodTag?.trim();

    if (!playlistName) {
      return NextResponse.json({ error: 'Playlist name is required' }, { status: 400 });
    }
    // Check if the user already has a playlist with the same name to prevent duplicates
    const [existingRows] = await pool.query(
      `SELECT playlist_id
       FROM playlists
       WHERE user_id = ? AND playlist_name = ?
       LIMIT 1`,
      [userId, playlistName]
    );

    if (existingRows.length) {
      return NextResponse.json(
        { error: 'You already have a playlist with that name' },
        { status: 409 }
      );
    }

    // Insert the new playlist into the database
    const [result] = await pool.query(
      `INSERT INTO playlists (user_id, playlist_name, mood_tag)
       VALUES (?, ?, ?)`,
      [userId, playlistName, moodTag || null]
    );

    return NextResponse.json(
      {
        ok: true,
        message: 'Playlist created successfully',
        playlist: {
          id: result.insertId,
          userId,
          playlistName,
          moodTag: moodTag || null,
        },
      },
      { status: 201 }
    );
  } catch (error) {
    console.error('Add playlist route error:', error);
    return NextResponse.json({ error: 'Failed to create playlist' }, { status: 500 });
  }
}

//DELETE request for playlist deletion
//Action will delete a playlist from front end and database
export async function DELETE(request) {
  try{
    const cookieUserId = request.cookies.get('karaoke_user_id')?.value;
    const userId = Number(cookieUserId);

    if (!Number.isInteger(userId) || userId < 1) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await request.json();
    const playlistId = body.playlistId;

    if (!playlistId) {
      return NextResponse.json({ error: 'Playlist ID is required' }, { status: 400 });
    }

    // Delete the playlist from the database, based on the logged-in user 
    const [result] = await pool.query(
      `DELETE FROM playlists
       WHERE playlist_id = ? AND user_id = ?`,
      [playlistId, userId]
    );

    if (result.affectedRows === 0) {
      return NextResponse.json({ error: 'Playlist not found' }, { status: 404 });
    }

    return NextResponse.json({ ok: true, message: 'Playlist deleted successfully' }, { status: 200 });      
    } catch (error) {   
      console.error('Delete playlist route error:', error);
      return NextResponse.json({ error: 'Failed to delete playlist' }, { status: 500 });  

  }
}

// PUT request for playlist updates (playlist name and mood tag) - this will update the playlist name and mood tag for a given playlist ID, but only if the playlist belongs to the currently logged-in user (based on the session cookie)
export async function PUT(request) {
  try {
    const cookieUserId = request.cookies.get('karaoke_user_id')?.value;
    const userId = Number(cookieUserId);

    if (!Number.isInteger(userId) || userId < 1) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await request.json();
    const playlistId = Number(body.playlistId);
    const playlistName = body.playlistName?.trim();
    const moodTag = body.moodTag?.trim();

    if (!Number.isInteger(playlistId) || playlistId < 1) {
      return NextResponse.json({ error: 'Playlist ID is required' }, { status: 400 });
    }

    if (!playlistName) {
      return NextResponse.json({ error: 'Playlist name is required' }, { status: 400 });
    }

    // Check if the user already has a playlist with the same name (excluding the current playlist) to prevent duplicates
    //Updating Playlist name and mood tag
    const [existingRows] = await pool.query(
      `SELECT playlist_id
       FROM playlists
       WHERE user_id = ? AND playlist_name = ? AND playlist_id <> ?
       LIMIT 1`,
      [userId, playlistName, playlistId]
    );

    if (existingRows.length) {
      return NextResponse.json(
        { error: 'You already have a playlist with that name' },
        { status: 409 }
      );
    }

    const [result] = await pool.query(
      `UPDATE playlists
       SET playlist_name = ?, mood_tag = ?
       WHERE playlist_id = ? AND user_id = ?`,
      [playlistName, moodTag || null, playlistId, userId]
    );

    if (result.affectedRows === 0) {
      return NextResponse.json({ error: 'Playlist not found' }, { status: 404 });
    }

    return NextResponse.json(
      {
        ok: true,
        message: 'Playlist updated successfully',
        playlist: {
          id: playlistId,
          userId,
          playlistName,
          moodTag: moodTag || null,
        },
      },
      { status: 200 }
    );
  } catch (error) {
    console.error('Update playlist route error:', error);
    return NextResponse.json({ error: 'Failed to update playlist' }, { status: 500 });
  }
}